### ISSUE TITLE
Crash while picking image from google photos (saved on cloud)

### ISSUE THREAD

**Issue by raviteja06** [fabian7593/MagicalCamera#1]
Here is the stacktrace

`Process: com.frosquivel.examplemagicalcamera, PID: 15830
                                                                                     java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/0/1/mediakey:/AF1QipOTHiNpPGT68W__NicJcUXV205tCyCXoYObDFDe/ORIGINAL/NONE/614175862 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2FAF1QipOTHiNpPGT68W__NicJcUXV205tCyCXoYObDFDe/ORIGINAL/NONE/614175862} }} to activity {com.frosquivel.examplemagicalcamera/com.frosquivel.examplemagicalcamera.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:3720)
                                                                                         at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
                                                                                         at android.app.ActivityThread.access$1400(ActivityThread.java:154)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                         at com.frosquivel.magicalcamera.MagicalCamera.resizePhoto(MagicalCamera.java:322)
                                                                                         at com.frosquivel.magicalcamera.MagicalCamera.onSelectFromGalleryResult(MagicalCamera.java:215)
                                                                                         at com.frosquivel.magicalcamera.MagicalCamera.resultPhoto(MagicalCamera.java:185)
                                                                                         at com.frosquivel.examplemagicalcamera.MainActivity.onActivityResult(MainActivity.java:71)
                                                                                         at android.app.Activity.dispatchActivityResult(Activity.java:6470)
                                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
                                                                                         at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763) 
                                                                                         at android.app.ActivityThread.access$1400(ActivityThread.java:154) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

**Comment by fabian7593** [comment]
Yes, originally the library is only for photos that stay in the memory device not in cloud...
I dont have any picture in cloud or an integration in my device for reproduce the error,
Can you reproduce the error and maybe fix this, remember is open source and free you have the posibility of change anything that you need ...
Really thanks bro!

**Comment by fabian7593** [comment]
MagicalCamera only support physical pictures, not in cloud, maybe for the next versions I will it in mind
