### ISSUE TITLE
NoClassDefFoundError when using imageView.setImageBitmap(magicalCamera.faceDetector())

### ISSUE THREAD

**Issue by riadrifai22** [fabian7593/MagicalCamera#18]
```
FATAL EXCEPTION: main
                                                                   Process: com.facedetection, PID: 25183
                                                                   java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/vision/face/FaceDetector$Builder;
                                                                       at com.frosquivel.magicalcamera.Functionallities.FaceRecognition.faceDetection(FaceRecognition.java:68)
                                                                       at com.frosquivel.magicalcamera.Functionallities.FaceRecognition.faceDetector(FaceRecognition.java:51)
                                                                       at com.frosquivel.magicalcamera.MagicalCamera.faceDetector(MagicalCamera.java:109)
                                                                       at com.facedetection.MagicBaby.onActivityResult(MagicBaby.java:73)
                                                                       at android.app.Activity.dispatchActivityResult(Activity.java:7137)
                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:4921)
                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4968)
                                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:222)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1849)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:158)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.vision.face.FaceDetector$Builder" on path: DexPathList[[zip file "/data/app/com.facedetection-1/base.apk"],nativeLibraryDirectories=[/data/app/com.facedetection-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                       at com.frosquivel.magicalcamera.Functionallities.FaceRecognition.faceDetection(FaceRecognition.java:68) 
                                                                       at com.frosquivel.magicalcamera.Functionallities.FaceRecognition.faceDetector(FaceRecognition.java:51) 
                                                                       at com.frosquivel.magicalcamera.MagicalCamera.faceDetector(MagicalCamera.java:109) 
                                                                       at com.facedetection.MagicBaby.onActivityResult(MagicBaby.java:73) 
                                                                       at android.app.Activity.dispatchActivityResult(Activity.java:7137) 
                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:4921) 
                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4968) 
                                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:222) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1849) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:158) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                   	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.vision.face.FaceDetector$Builder
                                                                       at java.lang.Class.classForName(Native Method)
                                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                       		... 16 more
                                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

I have all permissions in manifest and requested all permissions at runtime.

**Comment by fabian7593** [comment]
Were you use the example of magical camera? (in the directory app, of the repository)... if you use this example, you don't need to have this issue...

Can you test the example and verify if If you get the error again, please? If all Is great I need to view your code of permission and magical camera declaration and the use of face detector camera for view more the problem...

Thanks for use magical camera @riadrifai22

**Comment by riadrifai22** [comment]
@fabian7593 
Alright here are the details, I integrated the library through gradle to test it, the app is one activity which I will write below. I will also add the manifest under. And I have tested the example and it is still crashing. 
(I'm thinking of integrating the library with my app so any help would be appreciated)

Here is the code: 

MagicBaby.java (this is how i choose my test classes' names lol)

```

import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.Toast;

import com.frosquivel.magicalcamera.Functionallities.PermissionGranted;
import com.frosquivel.magicalcamera.MagicalCamera;

public class MagicBaby extends AppCompatActivity {


    MagicalCamera magicalCamera;

    Button button;
    ImageView imageView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_magic_baby);
        button = (Button) findViewById(R.id.button_magical);
        imageView = (ImageView) findViewById(R.id.imageView_magical);

        //The parameter this, is the current activity
        PermissionGranted permissionGranted = new PermissionGranted(this);

        //permission for take photo, it is false if the user check deny
        //permissionGranted.checkCameraPermission();

        //permission for location for use the `photo information device.
        //permissionGranted.checkLocationPermission();

        permissionGranted.checkAllMagicalCameraPermission();

        magicalCamera = new MagicalCamera(this,80, permissionGranted);

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //take photo
                magicalCamera.takePhoto();
            }
        });
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        magicalCamera.permissionGrant(requestCode, permissions, grantResults);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        //magicalCamera.resultPhoto(requestCode, resultCode, data);

        //CALL THIS METHOD EVER
        magicalCamera.resultPhoto(requestCode, resultCode, data);

        //this is for rotate picture in this method
        //magicalCamera.resultPhoto(requestCode, resultCode, data, MagicalCamera.ORIENTATION_ROTATE_180);

        //with this form you obtain the bitmap (in this example set this bitmap in image view)
        //imageView.setImageBitmap(magicalCamera.getPhoto());

        if(magicalCamera != null){
            if(magicalCamera.getPhoto() != null){
                //this comment line is the strok 5 and color red for default
                //imageView.setImageBitmap(magicalCamera.faceDetector());
                //you can the posibility of send the square color and the respective stroke
                //imageView.setImageBitmap(magicalCamera.faceDetector(50, Color.GREEN));


                //// TODO: 11-03-17 The crash is happening here 
                Bitmap bitmap = magicalCamera.faceDetector(50, Color.GRAY);

                // List<Landmark> listMark = magicalCamera.getListLandMarkPhoto();
            }else{
                Toast.makeText(MagicBaby.this,
                        "Your image is null, please select or take one",
                        Toast.LENGTH_SHORT).show();
            }
        }else{
            Toast.makeText(MagicBaby.this,
                    "Please initialized magical camera, maybe in static context for use in all activity",
                    Toast.LENGTH_SHORT).show();
        }
    }

    
}
```
Also, not sure if this matters, but is the **Landmark** is part of the library? Because it couldn't be imported. Also **magicalCamera.getListLandMarkPhoto();** wasn't being found.

Below is my Manifest permissions:

```
<uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES" />
    <uses-permission android:name="android.permission.MANAGE_DOCUMENTS" />

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

Thanks in advance, and great job so far you guys

**Comment by riadrifai22** [comment]
Never mind it worked, it was my fault I forgot to add a gms dependency. 
Thanks
