### ISSUE TITLE
NullPointerException 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by jeronimosodero** [fabian7593/MagicalCamera#21]
Hi. I get the following crash when taking pictures. But doesn't happen every time.
`java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3720)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
	at android.app.ActivityThread.-wrap16(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.frosquivel.magicalcamera.Utilities.PictureUtils.resizePhoto(PictureUtils.java:43)
	at com.frosquivel.magicalcamera.Functionallities.ActionPicture.onTakePhotoResult(ActionPicture.java:221)
	at com.frosquivel.magicalcamera.Functionallities.ActionPicture.resultPhoto(ActionPicture.java:240)
	at com.frosquivel.magicalcamera.MagicalCamera.resultPhoto(MagicalCamera.java:163)
	at ar.com.nabla.sistemalecturas.fragment.UnidadFragment.onActivityResult(UnidadFragment.java:1167)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at ar.com.nabla.sistemalecturas.activity.UnidadActivity.onActivityResult(UnidadActivity.java:162)
	at android.app.Activity.dispatchActivityResult(Activity.java:6442)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
	... 9 more`

**Comment by fabian7593** [comment]
@jerosode hello,
Interesting issue, I never view that in any devices, but only test in Huawei brand, Samsung and Emulator devices,
Can you give me more details please?
What brand of devices that you use?
What version API you have in device and you use in your app?
What is the percentage of the quality picture?
In which cases does it happen?

Thanks,

**Comment by jeronimosodero** [comment]
Hi. Yes. All the devices are:

- Motorola Moto g3 running Android 6.0
- minSdkVersion 21
- targetSdkVersion 25
- compileSdkVersion 25
- PHOTO_QUALITY 25%
I could not replicate the crash yet in any emulator or my device (Motorola Moto g 1st gen running 7.1.1)
Thanks to you.

**Comment by fabian7593** [comment]
Thanks to you for use magical Camera
