### ISSUE TITLE
Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)

### ISSUE THREAD

**Issue by ardakaplan** [fabian7593/MagicalCamera#34]
I never go with that but in application on store some devices gettings this error when asking permission.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.frosquivel.magicalcamera.MagicalPermissions.executeRequestPermission(MagicalPermissions.java:126)
       at com.frosquivel.magicalcamera.MagicalPermissions.requestPermissions(MagicalPermissions.java:78)
       at com.frosquivel.magicalcamera.MagicalPermissions.askPermissions(MagicalPermissions.java:61)
       at com.ardroid.allaboutus.ui.fragments.profile.ProfileMainFragment.askPermission(ProfileMainFragment.java:236)
       at com.ardroid.allaboutus.ui.fragments.profile.ProfileMainFragment.getUserImage(ProfileMainFragment.java:218)
       at com.ardroid.allaboutus.ui.fragments.profile.ProfileMainFragment_ViewBinding$1.doClick(ProfileMainFragment_ViewBinding.java:44)
       at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
       at android.view.View.performClick(View.java:6261)
       at android.view.View$PerformClick.run(View.java:23748)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by fabian7593** [comment]
Thanks for report the issue I review and fix this in other version

**Comment by tk2232** [comment]
The same problem on the pixel 1.
