### ISSUE TITLE
Crashing on takePhoto

### ISSUE THREAD

**Issue by vishalgupta1987** [fabian7593/MagicalCamera#36]
Device - Xiomi A1
OS - 8.0.0

App is crashing when we take photo and magicalCamera.resultPhoto(requestCode, resultCode, data); is crashing in onActivityResult.

I have also tested your application on Google Play, that is also crashing.

Logs:
Process: com.test.imagesearch, PID: 24454
                                                   java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=null} to activity {com.test.imagesearch/com.test.imagesearch.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:4348)
                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4391)
                                                       at android.app.ActivityThread.-wrap19(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:172)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6637)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                       at com.frosquivel.magicalcamera.Utilities.PictureUtils.resizePhoto(PictureUtils.java:43)
                                                       at com.frosquivel.magicalcamera.Functionallities.ActionPicture.onTakePhotoResult(ActionPicture.java:184)
                                                       at com.frosquivel.magicalcamera.Functionallities.ActionPicture.resultPhoto(ActionPicture.java:203)
                                                       at com.frosquivel.magicalcamera.MagicalCamera.resultPhoto(MagicalCamera.java:206)
                                                       at com.test.imagesearch.MainActivity.onActivityResult(MainActivity.java:123)
                                                       at android.app.Activity.dispatchActivityResult(Activity.java:7235)
                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:4344)

**Comment by fabian7593** [comment]
Interesting result, 
I review the app in google play in this days, for fix this issues in other version

**Comment by g00m** [comment]
I have the same problem on all my devices: 

Nexus 5X (Android 8)
Sony Z5 Compact (Android 7.1)
Galaxy S5 (Android 6)

I think the problem ist somewhere in reading a the bitmap after the image was taken. Looks like android can not read from "takenPhotoUri".

**Comment by sebamena** [comment]
Some solution for this?

**Comment by mariolourobert** [comment]
+1
Some solution ?

**Comment by makhmudov** [comment]
I have the same problem. Did you find any solution?

**Comment by bartpanic** [comment]
I have the same problem with android 8 oreo. Did you find any solution?

**Comment by sebamena** [comment]
Finally i have to change this lib.

**Comment by alanbarboza** [comment]
> Finally i have to change this lib.

@sebamena what lib did you used?

**Comment by SaulDuenas** [comment]
any solution for this issue ?

**Comment by fabian7593** [comment]
Could you test the new version of magical camera?
Please view the 6.0.0 version, the code is the same...
I fix it and add support for SDK 25+
Sorry for any incovenient.
