### ISSUE TITLE
NullPointerException - Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by sebamena** [fabian7593/MagicalCamera#43]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at com.frosquivel.magicalcamera.Utilities.PictureUtils.resizePhoto(PictureUtils.java:43)
       at com.frosquivel.magicalcamera.Functionallities.ActionPicture.onTakePhotoResult(ActionPicture.java:184)
       at com.frosquivel.magicalcamera.Functionallities.ActionPicture.resultPhoto(ActionPicture.java:203)
       at com.frosquivel.magicalcamera.MagicalCamera.resultPhoto(MagicalCamera.java:206)
       at com.example.luis.myapplication.views.SubsectorActivity.onActivityResult(SubsectorActivity.java:1451)
       at android.app.Activity.dispatchActivityResult(Activity.java:6442)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by mariolourobert** [comment]
+1
Any solution ?

**Comment by carlabalbontin** [comment]
+1

**Comment by hangocanh2303** [comment]
any solution?

**Comment by joshuakaleb0424** [comment]
Anyone who made progress with this?

**Comment by fabian7593** [comment]
I upload a new version on this week, if you have a lot of time to test that... because on my devices works correctly and on emulator same...

**Comment by fabian7593** [comment]
https://github.com/fabian7593/MagicalCamera/issues/36#issuecomment-466699668
