### ISSUE TITLE
[bug-android 8] java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by hangocanh2303** [fabian7593/MagicalCamera#45]
Hi 
When i use this library in android 8.0. It show this error 
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at com.frosquivel.magicalcamera.Utilities.PictureUtils.resizePhoto(PictureUtils.java:44)
       at com.frosquivel.magicalcamera.Functionallities.ActionPicture.onTakePhotoResult(ActionPicture.java:184)
       at com.frosquivel.magicalcamera.Functionallities.ActionPicture.resultPhoto(ActionPicture.java:203)
       at com.frosquivel.magicalcamera.MagicalCamera.resultPhoto(MagicalCamera.java:206)
       at com.anphuocthai.vn.activitys.customer.ListImageAlreadyCheckInActivity.onActivityResult(ListImageAlreadyCheckInActivity.java:387)
       at android.app.Activity.dispatchActivityResult(Activity.java:7556)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
       at android.app.ActivityThread.-wrap20(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Please fix this error, for better library

**Comment by fabian7593** [comment]
https://github.com/fabian7593/MagicalCamera/issues/36#issuecomment-466699668
