### ISSUE TITLE
NullPointerException name 

### ISSUE THREAD

**Issue by avew** [fabian7593/MagicalCamera#5]
`
java.lang.RuntimeException: Unable to resume activity {com.frosquivel.examplemagicalcamera/com.frosquivel.examplemagicalcamera.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=null} to activity {com.frosquivel.examplemagicalcamera/com.frosquivel.examplemagicalcamera.MainActivity}: java.lang.NullPointerException: name == null
                                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2790)
                                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2254)
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5052)
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                                    Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=null} to activity {com.frosquivel.examplemagicalcamera/com.frosquivel.examplemagicalcamera.MainActivity}: java.lang.NullPointerException: name == null
                                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3367)
                                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2777)
                                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819) 
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2254) 
                                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5052) 
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                                    Caused by: java.lang.NullPointerException: name == null
                                                                                       at java.io.File.<init>(File.java:150)
                                                                                       at java.io.File.<init>(File.java:124)
                                                                                       at com.frosquivel.magicalcamera.MagicalCamera.getPhotoFileUri(MagicalCamera.java:349)
                                                                                       at com.frosquivel.magicalcamera.MagicalCamera.onTakePhotoResult(MagicalCamera.java:229)
                                                                                       at com.frosquivel.magicalcamera.MagicalCamera.resultPhoto(MagicalCamera.java:191)
                                                                                       at com.frosquivel.examplemagicalcamera.MainActivity.onActivityResult(MainActivity.java:81)
                                                                                       at android.app.Activity.dispatchActivityResult(Activity.java:5437)
                                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3363)
                                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2777) 
`

**Comment by beingentangled** [comment]
I've got the same problem

**Comment by fabian7593** [comment]
Hello, can you Give me the device brand and android version that you use for run the test?, and do you have any SD Card in the devices or not? 

With this answer I can try to fix yours issues...

Thanks for use my library and Im sorry for this problem...

**Comment by avew** [comment]
i am using Xiaomi redmi 1s and i have SD Card

**Comment by beingentangled** [comment]
hello @avew . It's null pointer problem where the data is returned as null . I solved it by 
//make sure to put this line
   `mMagicalCamera.resultPhoto(requestCode, resultCode, data);`
add this for checking:

```
 if(mMagicalCamera.getMyPhoto()!=null){
            SaveImage(mMagicalCamera.getMyPhoto());
        }
```

**Comment by fabian7593** [comment]
Hello @avew 
I review the code and I can think that this problem appear because your device not recognizer the SDCARD (with my code), and  as a matter of fact this should not have any error, but I can did find a  posible fix in these days... please realize the test with this code (remember de OVERRIDE and the super method)

@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        magicalCamera.resultPhoto(requestCode, resultCode, data);

```
      if(magicalCamera.getMyPhoto()!=null){
          magicalCamera.savePhotoInMemoryDevice(magicalCamera.getMyPhoto(),"myTestPhoto",                  MagicalCamera.JPEG, true)
    }
```

}

If you dont fix that, please download my code and test with my own code of the example, withouh change anything...

And if this dont fix anything, dont worry, plase tell me.
I hope upload the version 2.0 with some fixes and another functionallities in the next month maybe.

@Binzzzz Thanks for help us with my errors :( 

and thanks to you for use the library :D

**Comment by johan-schoeman** [comment]
I had a similar problem as avew in the first post and changed the code of method writePhotoFile in class MagicalCamera.java to:

```
private boolean writePhotoFile(Bitmap bitmap, String photoName, String directoryName,
                               Bitmap.CompressFormat format, boolean autoIncrementNameByDate){
  if (bitmap == null) { 
    return false;
  } else {  
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();
    bitmap.compress(format, 100, bytes);

    DateFormat df = new SimpleDateFormat("yyyyMMddHHmmss");
    String date = df.format(Calendar.getInstance().getTime());

    String newPhotoName;
    if(format == PNG){
        newPhotoName = autoIncrementNameByDate ?  photoName + "_" + date + ".png" : photoName + ".png";
    }else if (format == JPEG){
        newPhotoName = autoIncrementNameByDate ?  photoName + "_" + date + ".jpeg" : photoName + ".jpeg";
    }else if (format == WEBP){
        newPhotoName = autoIncrementNameByDate ?  photoName + "_" + date + ".webp" : photoName + ".webp";
    } else {
        newPhotoName = photoName;
    }

    File wallpaperDirectory = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES + "/" + directoryName + "/");
    if (!wallpaperDirectory.exists()) {
        wallpaperDirectory.mkdirs();
    }
    File f = new File(wallpaperDirectory,newPhotoName);

    try {
        f.createNewFile();
        FileOutputStream fo = new FileOutputStream(f);
        fo.write(bytes.toByteArray());
        fo.close();
        this.activity.sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE,
                Uri.parse("file://"+f.getAbsolutePath())));

        return true;
    }catch (Exception ev){
        return false;
    }
  }

}
```

**Comment by martiwi** [comment]
On my side, on a Samsung galaxy S4, using Fragment, it happens that when returning to the Fragment, a rotation occured causing the Activity to be re-created and thuse the instance of MagicalCamera was created again.
I solved this by calling this.magicalCamera.takeFragmentPhoto(); after object initialization. And saving in onSaveInstanceState the bitmap to get it back in onViewStateRestored.

**Comment by jeronimosodero** [comment]
I have the same problem when using Fragments. It only happens when rotating and when I debug I think the problem is in the method: onTakePhotoResult() , first line. Because this.thePhotoName and this.anotherPhotoName are null, when both have to be equal to "MagicalCamera". this.activity is not null.

**Comment by fabian7593** [comment]
Can you declare the variable of MagicalCamera in the "head" of the .java like a static variable (because you need to maintenance the intance in all of your screen activity or fragment)...
for example declare:
private static MagicalCamera magicalCamera;

and for example in the onCreate made the instance:
magicalCamera = new MagicalCamera(this,2500);

Test with this, whiith this option you dont have to take a variable null...
Thanks to everywhere and sorry for the Issues

**Comment by fabian7593** [comment]
if you have any problem when you rotate the camera you try to fix this with android:configChanges="orientation|screenSize" in the options of your activities (in the manifest).
of save the state of the variables or image view with another methods, (but this is the more easy :D)

**Comment by fabian7593** [comment]
Hello @avew, @jerosode , @martiwi , @johan-schoeman , @Binzzzz ... Can you test the new version of magical camera? 5.0.2 ... I really enthusiastic because this issues are closed, download the new example and use magical camera, thanks for everything, and Im sorry for the last problems,
